name: gyawun
base: core22
version: 1.0.0
summary: GyawunMusic – A modern Flutter music player
description: "GyawunMusic is a powerful, plugin-capable music app built with Flutter."

grade: stable
confinement: strict

apps:
  gyawun:
    command: gyawun
    extensions: [gnome]
    plugs:
      - opengl
      - network
      - audio-playback
      - home
      - removable-media
      - mpris
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  gyawun:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    stage-packages:
      - mpv
    # override-build: |
    #   export PKG_CONFIG_PATH=$SNAPCRAFT_STAGE/lib/pkgconfig:$PKG_CONFIG_PATH
    #   snapcraftctl build