name: gyawun-music
base: core22
version: '0.1.0' 
summary: A beautiful music player for Linux built with Flutter.
description: |
  Gyawun Music is an elegant and feature-rich music player designed for the
  Linux desktop. Enjoy your local music library with a smooth and intuitive
  interface, powered by mpv for high-quality audio playback.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  gyawun-music:
    command: gyawun_music 
    extensions: [flutter-master]
    plugs:
      - opengl
      - network
      - audio-playback
      - home
      - removable-media
      - mpris
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  gyawun-music:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart 
    build-packages:
      - libmpv-dev
    stage-packages:
      - libmpv2

